import sys
import os
import pandas as pd
import datetime
import json
from pathlib import Path

# Add backend to path
sys.path.append(str(Path(__file__).resolve().parent.parent))

from app.database import SessionLocal, engine, Base
from app.models.consumption import ConsumptionHistory
from sqlalchemy import text

MAPPED_LOCATIONS = ["Loc_3", "Loc_7", "Loc_15"]

def generate_context_file(df):
    print("Generating andaza_context.py...")
    # Calculate seasonal weather (monthly averages per location)
    # df has Location_ID, Month, Temp_Celsius, Rain_mm
    seasonal = df.groupby(["Location_ID", "Month"])[["Temp_Celsius", "Rain_mm"]].mean().reset_index()
    weather_dict = {}
    for _, row in seasonal.iterrows():
        loc = row["Location_ID"]
        month = int(row["Month"])
        if loc not in weather_dict:
            weather_dict[loc] = {}
        weather_dict[loc][month] = {
            "temp_celsius": float(row["Temp_Celsius"]),
            "rain_mm": float(row["Rain_mm"])
        }

    # Calculate recent averages (we'll just use the last 30 days of available data per location)
    # The max date is 2025-12-31 usually.
    recent_averages = {}
    for loc in df['Location_ID'].unique():
        loc_df = df[df['Location_ID'] == loc].sort_values('Date').tail(30)
        recent_averages[loc] = {
            "reservations": int(loc_df["Reservations"].mean()),
            "cpi_index": float(loc_df["CPI_Index"].mean()),
            "online_rating": float(loc_df["Online_Rating"].mean()),
            "competitor_promo": int(loc_df["Competitor_Promo"].mode()[0])
        }

    context_code = f'''"""
Auto-generated by seed_andaza.py
Contains climatology fallbacks, KITCHEN_LOCATION_MAP, and holiday/events config.
"""

KITCHEN_LOCATION_MAP = {{
    "K1_MainCampus": "Loc_3",
    "K2_HostelBlockA": "Loc_7",
    "K3_HostelBlockB": "Loc_15"
}}

SEASONAL_WEATHER = {json.dumps(weather_dict, indent=4)}

RECENT_AVERAGES = {json.dumps(recent_averages, indent=4)}

# Simple Indian public holiday table (example for Sep/Oct 2026)
PUBLIC_HOLIDAYS = {{
    "2026-01-26", "2026-08-15", "2026-10-02", "2026-11-01"
}}

# Config table for local events/promotions
LOCAL_EVENTS = {{
    # "YYYY-MM-DD": {{"local_event": 1, "active_promotion": 1}}
}}
'''
    out_path = Path(__file__).resolve().parent.parent / "app" / "services" / "andaza_context.py"
    with open(out_path, "w") as f:
        f.write(context_code)
    print(f"Written to {out_path}")


def seed_database(df):
    print("Seeding ConsumptionHistory...")
    # Base.metadata.create_all(bind=engine) # Already done in main or startup, but let's be sure
    
    # We only care about the 3 mapped locations
    df_filtered = df[df['Location_ID'].isin(MAPPED_LOCATIONS)].copy()
    df_filtered['Date'] = pd.to_datetime(df_filtered['Date'])
    
    db = SessionLocal()
    
    # Clear existing
    db.query(ConsumptionHistory).delete()
    
    # Insert actual history
    records = []
    for _, row in df_filtered.iterrows():
        records.append(ConsumptionHistory(
            location_id=row['Location_ID'],
            date=row['Date'].date(),
            customer_count=row['Customer_Count']
        ))
    
    # Generate synthetic bridge from Jan 2026 to Dec 2026
    # To maintain weekly seasonality, we map Date D to (D - 364 days), which is exact 52 weeks ago.
    print("Generating synthetic bridge for 2026...")
    max_date = df_filtered['Date'].max()
    end_date = datetime.date(2026, 12, 31)
    
    current_date = max_date.date() + datetime.timedelta(days=1)
    
    # Create lookup dictionary from the actual data for quick synthetic generation
    lookup = {}
    for _, row in df_filtered.iterrows():
        lookup[(row['Location_ID'], row['Date'].date())] = row['Customer_Count']
        
    while current_date <= end_date:
        # Shift back 364 days (52 weeks exactly, maintains day of week)
        historical_date = current_date - datetime.timedelta(days=364)
        for loc in MAPPED_LOCATIONS:
            # Fallback to mean if for some reason missing
            count = lookup.get((loc, historical_date), 300)
            records.append(ConsumptionHistory(
                location_id=loc,
                date=current_date,
                customer_count=count
            ))
            # Also put into lookup in case we need to look back further than 1 year
            lookup[(loc, current_date)] = count
            
        current_date += datetime.timedelta(days=1)
        
    # Bulk insert
    db.bulk_save_objects(records)
    db.commit()
    db.close()
    print(f"Seeded {len(records)} records into ConsumptionHistory.")


if __name__ == "__main__":
    csv_path = Path(__file__).resolve().parent.parent.parent / "restaurant_demand_28k.csv"
    if not csv_path.exists():
        print(f"CSV not found at {csv_path}")
        sys.exit(1)
        
    df = pd.read_csv(csv_path)
    generate_context_file(df)
    
    Base.metadata.create_all(bind=engine)
    seed_database(df)
    print("Done.")
